video: fbdev: starfive: Use round_up() instead of _ALIGN_UP()
_ALIGN_UP() is being removed by commit efcec32fe84ab4ee ("riscv: Cleanup
unused functions") in riscv/for-next:

    drivers/video/fbdev/starfive/starfive_displayer.c: In function ‘of_parse_wr_cmd’:
    drivers/video/fbdev/starfive/starfive_displayer.c:616:27: error: implicit declaration of function ‘_ALIGN_UP’ [-Werror=implic
    it-function-declaration]
      616 |  dev_cmds->cmds = kzalloc(_ALIGN_UP(alloc_bytes, 4), GFP_KERNEL);
	  |                           ^~~~~~~~~

Just use roundup() instead.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Tested-by: Emil Renner Berthing <kernel@esmil.dk>